import jsPDF from "jspdf";
import { performanceMetrics, financialData, energyData } from "@/data/mock-data";

// Monthly Performance Report
export function generateMonthlyPerformancePDF() {
  const doc = new jsPDF();

  doc.setFontSize(18);
  doc.text("Monthly Performance Report", 20, 20);

  doc.setFontSize(12);
  doc.text(`PR %: ${performanceMetrics.pr}`, 20, 40);
  doc.text(`CUF: ${performanceMetrics.cuf}`, 20, 50);
  doc.text(`Degradation: ${performanceMetrics.degradation}%/yr`, 20, 60);
  doc.text(`System Efficiency: ${performanceMetrics.efficiency}%`, 20, 70);

  doc.setFontSize(10);
  doc.text("Generated by Executive Dashboard", 20, 280);

  doc.save("monthly-performance-report.pdf");
}

// SLA Compliance Report
export function generateSLACompliancePDF() {
  const doc = new jsPDF();

  doc.setFontSize(18);
  doc.text("SLA Compliance Report", 20, 20);

  doc.setFontSize(12);
  doc.text(`Contract Demand: ${energyData.contractDemand} kW`, 20, 40);
  doc.text(`Current Max Demand: ${energyData.currentMaxDemand} kW`, 20, 50);
  doc.text(`Risk Level: ${energyData.riskLevel}`, 20, 60);
  doc.text(`Power Factor: ${energyData.powerFactor}`, 20, 70);

  doc.text("Recommendations:", 20, 90);
  energyData.recommendations.forEach((rec, i) => {
    doc.text(`- ${rec}`, 25, 100 + i * 10);
  });

  doc.setFontSize(10);
  doc.text("Generated by Executive Dashboard", 20, 280);

  doc.save("sla-compliance-report.pdf");
}

// Financial Summary Report
export function generateFinancialSummaryPDF() {
  const doc = new jsPDF();

  doc.setFont("times", "normal");
  doc.setFontSize(18);
  doc.text("Financial Summary Report", 20, 20);

  const formatINR = (val: number) => `₹${val.toLocaleString("en-IN")}`;

  doc.setFontSize(12);
  doc.text(`Monthly Revenue: ${formatINR(financialData.monthlyRevenue)}`, 20, 40);
  doc.text(`Expected Revenue: ${formatINR(financialData.expectedRevenue)}`, 20, 50);
  doc.text(`Revenue Gap: ${formatINR(financialData.revenueGap)}`, 20, 60);
  doc.text(`Annual Projection: ${formatINR(financialData.annualProjection)}`, 20, 70);

  doc.text("Loss Breakdown:", 20, 90);
  financialData.losses.forEach((loss, i) => {
    doc.text(
      `- ${loss.category}: ${formatINR(loss.amount)} (${loss.percentage}%)`,
      25,
      100 + i * 10
    );
  });

  doc.text("Cumulative Revenue (Expected vs Actual):", 20, 150);
  financialData.cumulativeRevenue.forEach((row, i) => {
    doc.text(
      `${row.month}: Expected ${formatINR(row.expected)}, Actual ${formatINR(row.actual)}`,
      25,
      160 + i * 8
    );
  });

  doc.text("Tariff Impact:", 20, 250);
  doc.text("Net Metering Balance: +1,240 kWh", 25, 260);
  doc.text("Export vs Self-Consumption: 35% / 65%", 25, 270);

  doc.setFontSize(10);
  doc.text("Generated by Executive Dashboard", 20, 280);

  doc.save("financial-summary.pdf");
}